"""empty message

Revision ID: 263667a9eaaa
Revises: bcf4a3010d10
Create Date: 2023-06-18 15:05:37.629917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263667a9eaaa'
down_revision = 'bcf4a3010d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fund_description', sa.String(length=800), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund', schema=None) as batch_op:
        batch_op.drop_column('fund_description')

    # ### end Alembic commands ###
