"""empty message

Revision ID: 35a9f0be651d
Revises: 263667a9eaaa
Create Date: 2023-06-19 16:19:11.086848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a9f0be651d'
down_revision = '263667a9eaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('working_package', schema=None) as batch_op:
        batch_op.drop_column('package_parent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('working_package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_parent', sa.VARCHAR(length=400), nullable=True))

    # ### end Alembic commands ###
